#pragma once

#include <cstdint>
#include <cstddef>
#include "shared_messages.h"

struct AudioUiState;
struct AppContext;

static constexpr size_t kMaxWavNameLen = 32;

class Ui
{
public:
	void Init(AppContext* ctx);
	void AccumulateControls(int32_t enc_l_inc,
							int32_t enc_r_inc,
							uint32_t ctrl_events,
							bool shift_held,
							bool btn1_held);
	void Tick(uint32_t now_ms);
	uint32_t& UiTickMsRef();
	uint32_t& UiTickPlaybackMsRef();
	bool IsDisplayUpdatePending() const;
	void SetLastDrawMs(uint32_t now_ms);
	UiMode GetMode() const;
	UiMode& ModeRef();
	int32_t& MenuIndexRef();
	int32_t& ShiftMenuIndexRef();
	int32_t& PerformIndexRef();
	int32_t& AmpFaderIndexRef();
	int32_t& FltFaderIndexRef();
	int32_t& FxFaderIndexRef();
	int32_t* FxChainOrderRef();
	const int32_t* FxChainOrder() const;
	bool& FxWindowActiveRef();
	bool& AmpWindowActiveRef();
	bool& FltWindowActiveRef();
	UiMode& ShiftPrevModeRef();
	RecordInput& RecordInputRef();
	RecordInput* GetRecordInputPtr();
	RecordState& RecordStateRef();
	int32_t& RecordSourceIndexRef();
	int32_t& RecordTargetIndexRef();
	uint32_t& RecordCountdownStartMsRef();
	size_t& RecordPosRef();
	size_t& RecordedLengthAudioRef();
	uint32_t& RecordStartMsRef();
	bool& RecordWaveformPendingRef();
	int32_t& EncoderRAccumRef();
	bool& EncoderRButtonPressRef();
	bool& RequestLengthRedrawRef();
	bool& RequestPlayheadRedrawRef();
	bool& Button1PressRef();
	bool& Button2PressRef();
	bool& RequestPlaybackStopLogRef();
	bool& PerformVoicesActiveRef();
	float& PlaybackAmpRef();
	uint32_t& PlaybackEnvSamplesRef();
	bool& PlaybackReleaseActiveRef();
	float& PlaybackReleasePosRef();
	float& PlaybackReleaseStartRef();
	int32_t& CurrentNoteRef();
	bool& AudioRecordingActiveRef();
	bool& ResetVoicesPendingRef();
	int32_t& ActiveVoiceCountRef();
	uint32_t& VoiceSkipCountRef();
	uint32_t& VoiceKillCountRef();
	float& DelayTimeAlphaRef();
	float& DelayParamAlphaRef();
	FxChainRuntime& FxChainAudioRef();
	bool& FxChainAudioValidRef();
	bool& PreviewHoldRef();
	bool& PreviewActiveRef();
	int32_t& PreviewIndexRef();
	uint16_t& PreviewChannelsRef();
	float& PreviewRateRef();
	float& PreviewReadFracRef();
	size_t& PreviewReadIndexRef();
	size_t& PreviewWriteIndexRef();
	uint32_t& PreviewDataOffsetRef();
	uint32_t& PreviewFadeSamplesLeftRef();
	uint32_t& PreviewFadeSamplesTotalRef();
	bool& PreviewPendingStartRef();
	uint32_t& PreviewPendingStartMsRef();
	uint32_t& PreviewUnderrunCountRef();
	uint32_t& PreviewRbMinLevelRef();
	uint16_t& PreviewStreamCookieRef();
	uint16_t& PreviewStreamCookieActiveRef();
	uint8_t* PreviewPpReadyPtr();
	uint8_t& PreviewPpActiveRef();
	uint32_t& PreviewPpPosRef();
	size_t& PreviewPreloadFramesRef();
	bool& PreviewPreloadActiveRef();
	float& Led1LevelRef();
	float& Led1PhaseMsRef();
	bool& RequestShiftRedrawRef();
	bool& RequestPerformRedrawRef();
	bool& RequestFxDetailRedrawRef();
	uint32_t& DelaySnowNextMsRef();
	uint32_t& MidiIgnoreUntilMsRef();
	bool& MidiRxStartedRef();
	bool& CtrlTimerRunningRef();
	float& TrimStartRef();
	float& TrimEndRef();
	uint32_t& SnapStartFrameRef();
	uint32_t& SnapEndFrameRef();
	bool& WaveformReadyRef();
	bool& WaveformDirtyRef();
	bool& WaveformFromRecordingRef();
	const char*& WaveformTitleRef();
	bool& WaveformComputePendingRef();
	SampleContext& WaveformComputeCtxRef();
	WaveformJob& WaveformJobRef();
	FileListJob& FileListJobRef();
	Job& JobRef();
	size_t& SampleMemUsedBytesRef();
	size_t& SampleMemFreeBytesRef();
	float& PerformAttackNormRef();
	float& PerformReleaseNormRef();
	float& ReverbWetRef();
	float& ReverbPreRef();
	float& ReverbDampRef();
	float& ReverbDecayRef();
	float& DelayWetRef();
	float& DelayTimeRef();
	float& DelayFeedbackRef();
	float& DelaySpreadRef();
	float& DelayFreezeRef();
	float& FxSWetRef();
	float& SatDriveRef();
	float& SatTapeBumpRef();
	float& SatBitResoRef();
	float& SatBitSmplRef();
	float& FxCWetRef();
	float& ModDepthRef();
	float& ChorusRateRef();
	int32_t& SatModeRef();
	int32_t& ChorusModeRef();
	float& ChorusWowRef();
	float& TapeRateRef();
	bool& FxParamsDirtyRef();
	bool& AudioParamsDirtyRef();
	bool& SatParamsInitializedRef();
	bool& ReverbParamsInitializedRef();
	bool& DelayParamsInitializedRef();
	bool& ModParamsInitializedRef();
	float& AmpAttackRef();
	float& AmpDecayRef();
	float& AmpSustainRef();
	float& AmpReleaseRef();
	int32_t& FxDetailIndexRef();
	int32_t& FxDetailParamIndexRef();
	float& FltCutoffRef();
	float& FltResRef();
	float& FxChainFadeGainRef();
	float& FxChainFadeTargetRef();
	int32_t& FxChainFadeSamplesLeftRef();
	bool& FxChainPausePendingRef();
	bool& FxChainPausedRef();
	uint32_t& FxChainLastMoveMsRef();
	AudioParams* AudioParamsBuf();
	uint8_t& AudioParamsPubIdxRef();
	uint8_t& AudioParamsActiveIdxRef();
	SampleRuntime* RtBuf();
	uint8_t& RtPubIdxRef();
	uint8_t& RtActiveIdxRef();
	FxChainRuntime* FxChainBuf();
	uint8_t& FxChainPubIdxRef();
	uint8_t& FxChainActiveIdxRef();
	PreviewControl* PreviewCtlBuf();
	uint8_t& PreviewPubIdxRef();
	uint8_t& PreviewActiveIdxRef();
	FxParamsAudio* FxParamsBuf();
	uint8_t& FxParamsIdxRef();
	AudioParamsAudio* AudioParamsAudioBuf();
	uint8_t& AudioParamsAudioIdxRef();
	AudioUiState* AudioUiStateBuf();
	uint8_t& AudioUiStateIdxRef();
	float& CpuLoadEmaRef();
	float& CpuLoadPctRef();
	float& CpuLoadPeakPctRef();
	uint32_t& CallbackCyclesLastRef();
	uint32_t& CallbackCyclesMaxRef();
	uint32_t& CallbackOverrunsRef();
	uint32_t& RecordDrawNextMsRef();
	double& RecordAnimStartMsRef();
	uint8_t (*RecordTextMask())[128];
	uint8_t (*RecordInvertMask())[128];
	uint8_t (*RecordFbBuf())[128];
	uint8_t (*RecordBoldMask())[128];
	size_t& WaveformCacheBytesRef();
	int32_t& LoadSelectedRef();
	int32_t& LoadScrollRef();
	bool& RequestLoadScanRef();
	bool& ListBuildPendingRef();
	bool& RequestLoadSampleRef();
	int32_t& RequestLoadIndexRef();
	bool& LoadInProgressRef();
	uint16_t& LoadCookieNextRef();
	uint16_t& LoadCookieActiveRef();
	bool& LoadTargetIsEdtRef();
	LoadContext& LoadContextRef();
	LoaderState& LoaderStateRef();
	uint32_t& LoadSuccessCountRef();
	uint32_t& LoadFailBudgetCountRef();
	uint32_t& LoadFailIoCountRef();
	int32_t& WavFileCountRef();
	bool& SdMountedRef();
	bool& SdPresentRef();
	bool& SdFaultRef();
	const char*& SdFaultTextRef();
	uint32_t& SdRetriesRemainingRef();
	bool& SdInitInProgressRef();
	bool& SdInitDoneRef();
	bool& SdInitSuccessRef();
	uint32_t& SdInitStartMsRef();
	uint32_t& SdInitNextMsRef();
	uint32_t& SdInitResultUntilMsRef();
	uint32_t& SdInitDrawNextMsRef();
	int32_t& SdInitAttemptsRef();
	UiMode& SdInitPrevModeRef();
	bool& SaveInProgressRef();
	bool& SaveDoneRef();
	bool& SaveSuccessRef();
	bool& SaveStartedRef();
	uint32_t& SaveStartMsRef();
	uint32_t& SaveResultUntilMsRef();
	uint32_t& SaveDrawNextMsRef();
	UiMode& SavePrevModeRef();
	size_t& SaveFramesWrittenRef();
	char* SaveFilename();
	bool& DeleteModeRef();
	UiMode& DeletePrevModeRef();
	bool& RequestDeleteScanRef();
	bool& RequestDeleteFileRef();
	int32_t& RequestDeleteIndexRef();
	bool& DeleteConfirmRef();
	char* DeleteConfirmName();
	bool& DeleteInProgressRef();
	uint16_t& DeleteCookieNextRef();
	uint16_t& DeleteCookieActiveRef();
	bool& RequestDeleteRedrawRef();
	UiMode& LoadPrevModeRef();
	UiMode& FxDetailPrevModeRef();
	UiMode& EdtPrevModeRef();
	float& PhonesVolumeRef();
	char (*WavFiles())[kMaxWavNameLen];
	char* LoadedSampleName();
	int32_t& LoadLinesRef();
	int32_t& LoadLineHeightRef();
	int32_t& LoadCharsPerLineRef();
	uint32_t& LoadScanStartMsRef();
	SampleContext& CurrentSampleContextRef();
	SampleContext& EdtSampleContextRef();
	int32_t& LoadModeIndexRef();
	LoadStubMode& LoadStubModeRef();
	size_t& SampleLengthRef();
	size_t& SamplePlayStartRef();
	size_t& SamplePlayEndRef();
	uint32_t& SampleRateRef();
	uint16_t& SampleChannelsRef();
	bool& SampleLoadedRef();
	bool& PlaybackActiveRef();
	float& PlaybackRateRef();
	float& PlaybackPhaseRef();
	float& PlaybackReverseRef();
	bool& PlaybackReverseTargetRef();
	bool& PlaybackReverseActiveRef();
	uint32_t& PreviewSampleRateRef();
	size_t GetWaveformCacheBytes() const;
};

void RequestDisplayUpdate();
void FlushDisplayIfDue(uint32_t now);

enum class LoadStubMode : int32_t;

void DrawMenu(int32_t selected);
void DrawPerformScreen(int32_t selected,
					   bool fx_select_active,
					   int32_t fx_selected,
					   bool amp_select_active,
					   int32_t amp_selected,
					   bool flt_select_active,
					   int32_t flt_selected,
					   uint8_t redraw_mask = 0x0F);
void DrawLoadMenu(int32_t top_index, int32_t selected);
void DrawLoadModeSelect(int32_t selected);
void DrawLoadStubScreen(LoadStubMode mode);
void DrawPresetSaveStub();
void DrawRecordReadyScreen();
void DrawRecordBackConfirm();
void DrawRecordSourceScreen();
void DrawRecordArmed();
void DrawRecordCountdown();
void DrawRecordRecording(const AudioUiState& ui_state);
void DrawRecordTargetScreen(int32_t selected);
void DrawRecordReview();
void DrawEdtScreen();
void DrawShiftMenu(int32_t selected);
void DrawSdInitScreen();
void DrawSaveScreen();
void DrawDeleteConfirm(const char* name);
void DrawFxDetailScreen(int32_t index);

void CopyString(char* dst, const char* src, size_t dst_len);

void UpdateDelaySlewCoeffs();
void InitSmoothers();
void UpdateSmoothedParamsPerTick();
void InitLoadLayout();
void ValidateConfig();
void MountSd();
bool IsPerformUiMode(UiMode mode);
void FinalizeFileList();
void PublishPreviewControlFromUi();
void StopPreview();
void JobStartWaveform(SampleContext ctx, bool foreground = true);
void UpdateTrimFrames();
void PublishRuntimeFromUi();
void PublishAudioParamsFromUi(const AudioParams& p);
float FxWetValue(int32_t fx_index);
void JobCancel();
void SetFxContext(FxContext ctx, int32_t track = 0);
void JobStartFileList(const char* path, bool wav_only, bool foreground = true);
bool LoadSampleAtIndex(int32_t index);
bool BeginPreviewAtIndex(int32_t index);
void FillPreviewBuffer();
bool DeleteFileAtIndex(int32_t index);
void ApplyLoadedSampleFade(size_t length, uint32_t rate);
